#!/usr/bin/env ruby

require 'faraday'
require 'json'

require './crittertrader_config.rb'

# Copies critters to a local directory, extracts them,
# renames them to a hash of their contents
class CritterHasher
  attr_reader :done

  def initialize(dir = "#{ENV['HOME']}/.critterding/save/exchange")
    @dir = dir
    @target_dir = 'exchange'
    @sleep_time
    @done = {}
  end

  def fulltarget(f)
    File.join(@target_dir, f)
  end

  def extract_local
    files = Dir.glob(File.join(@dir, '*cr*'))
    files.delete_if{|f| f =~ /^server/}

    fullbase = {}
    files.each do |f|
      fullbase[File.basename(f)] = f
    end

    puts "Extracting.."
    todo = fullbase.keys - @done.values
    todo.each do |f|
      fullname = fullbase[f]
      targetname = fulltarget(f)
      unzipped = targetname.gsub(/\.bz2$/, '')

      `cp '#{fullname}' '#{@target_dir}'`
      `bunzip2 '#{targetname}'`

      md5 = `md5sum '#{unzipped}'`
      md5 = md5.split.first

      hashname = File.join(@target_dir, md5)
      print "  #{f} -> #{md5} "

      if File.exist?(hashname)
        `rm '#{unzipped}'`
        puts "[already extracted]"
      else
        `mv '#{unzipped}' '#{hashname}'`
        puts "[new]"
      end

      @done[md5] = f
    end
    @done
  end

  def copy_back(files)
    puts "\nCopying back..."
    files.each do |f|
      critterfile = fulltarget(f)
      backfile = File.join(@dir, "server-#{f}.cr.bz2")

      print "  #{critterfile} "
      if @done[f]
        puts "[from local]"
      else
        if File.exist?(backfile)
          puts "[already exists]"
        else
          `bzip2 -c '#{critterfile}' > '#{backfile}'`
          @done[f] = critterfile
          puts " -> #{backfile}"
        end
      end
    end
  end
end

class CritterServer
  def initialize(host)
    @host = host
    @conn = Faraday.new(url: @host)
  end

  def get(path)
    @conn.get(path) do |req|
      req['Content-Type'] = 'application/json'
    end
  end

  def post(path, body)
    @conn.post(path) do |req|
      req['Content-Type'] = 'application/json'
      req.body = body
    end
  end

  def critters_get_all
    response = get('/critters')
    JSON.parse(response.body)['critters'].compact
  end

  def critters_get(hash)
    response = get("/critters/#{hash}")
    JSON.parse(response.body)['critter']['data']
  end

  def tokens_get
    response = get('/tokens')
    JSON.parse(response.body)['critter']['token']
  end

  def critters_post(file, token)
    data = File.read(file)
    body = {'critter' => {'token' => token, 'data' => data}}.to_json
    response = post('/critters', body)
    JSON.parse(response.body)
  end
end

class CritterUploader
  attr_reader :local_critters, :server_critters
  def initialize(critter_server, dir = "exchange")
    @cs = critter_server
    @dir = dir
  end

  def upload(file)
    token = @cs.tokens_get
    @cs.critters_post(file, token)
  end

  def upload_any
    @uploaded = []
    @server_critters = @cs.critters_get_all
    @local_critters = Dir.glob(File.join(@dir, '*')).map{|f| File.basename(f)}

    candidates = @local_critters - @server_critters
    if candidates.any?
      file = candidates[rand(candidates.length)]
      upload(File.join(@dir, file))
      @uploaded << file
    end

    @uploaded
  end

  def upload_all
    @uploaded = []
    @server_critters = @cs.critters_get_all
    @local_critters = Dir.glob(File.join(@dir, '*')).map{|f| File.basename(f)}

    candidates = @local_critters - @server_critters
    candidates.each do |file|
      upload(File.join(@dir, file))
      @uploaded << file
    end

    @uploaded
  end
end

class CritterDownloader
  def initialize(critter_server, dir = "exchange")
    @cs = critter_server
    @dir = dir
    @downloaded = []
  end

  def download(hash)
    file = File.join(@dir, hash)
    puts "Downloading #{file}"
    data = @cs.critters_get(hash)
    File.open(file, 'w'){|f| f.write(data)}
    @downloaded << hash
  end

  def download_any
    @downloaded = []
    @server_critters = @cs.critters_get_all
    @local_critters = Dir.glob(File.join(@dir, '*')).map{|f| File.basename(f)}

    candidates = @server_critters - @local_critters
    if candidates.any?
      hash = candidates[rand(candidates.length)]
      download(hash)
    end

    @downloaded
  end

  def download_all
    @downloaded = []
    @server_critters = @cs.critters_get_all
    @local_critters = Dir.glob(File.join(@dir, '*')).map{|f| File.basename(f)}

    candidates = @server_critters - @local_critters
    candidates.each do |hash|
      download(hash)
    end

    @downloaded
  end

end

class CritterTrader
  def initialize(critter_server)
    @ch = CritterHasher.new
    @cu = CritterUploader.new(critter_server)
    @cd = CritterDownloader.new(critter_server)
  end

  def run
    @ch.extract_local

    uploaded = @cu.upload_any
    puts uploaded.map{|f| "Uploaded #{f}"}.join("\n")
    puts "All local files uploaded" if !uploaded.any?

    downloaded = @cd.download_all
    puts downloaded.map{|f| "Downloaded #{f}"}.join("\n")
    puts "All server files downloaded" if !downloaded.any?

    @ch.copy_back(downloaded)
  end

  def run_forever
    loop do
      puts
      run

      # Sleep 10 minutes
      # PLEASE DON'T CHANGE THIS PEOPLE! I don't want the server to die.
      # In future we could probably tweak it, once I've optimised the server.
      puts "#{Time.now}: sleeping 10 minutes..."
      sleep(600)
    end
  end
end

if __FILE__ == $0
  config = CrittertraderConfig
  cs = CritterServer.new(config.host)
  ct = CritterTrader.new(cs)
  ct.run_forever
end

